baseURL = 'https://friends-of-lichess.github.io/'
languageCode = 'en-us'
title = 'Friends of Lichess, Inc.'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'Board of Directors'
    pageRef = '/board'
    weight = 20
  [[menu.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30

[params]
  background_color_class = "bg-dark-purple"
  [params.ananke]
    show_recent_posts = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
